version: "3.2"

services:
  web:
    image: odoo:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - data:/config/odoo
  db:
    image: postgres:latest
    restart: always
    volumes:
      - db:/config/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  caddy:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
  data:
  db:

networks:
  pod_network:
    driver: bridge




